// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.28;

// Auto-generated by cdm build for local project compilation. Do not edit by hand.
// CDM package: @tambola/tambola
// Local build stub only. cdm install/deploy replaces this file with an address-backed wrapper.

import "../../../contracts/Tambola.sol";

library TambolaTambola {
    address internal constant ADDRESS = 0x0000000000000000000000000000000000000000;

    function ref() internal pure returns (Tambola) {
        return Tambola(payable(ADDRESS));
    }

    function cdm() internal pure returns (Tambola) {
        return ref();
    }
}
