// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.28;

// Auto-generated by cdm install. Do not edit by hand.
// CDM package: @tambola/tambola
// CDM version: 9

struct ITambolaGameView {
    address host;
    uint256 ticketPrice;
    uint64 startTime;
    uint64 lastDrawTime;
    uint8 maxTickets;
    uint8 ticketCount;
    uint128 polledMask;
    uint256 pot;
    uint8 state;
    address[] topLineWinners;
    address[] middleLineWinners;
    address[] bottomLineWinners;
    address[] fullhouseWinners;
    uint256 drawnCount;
}

struct ITambolaTicket {
    address owner;
    uint128 fullhouseMask;
    uint128 topRowMask;
    uint128 middleRowMask;
    uint128 bottomRowMask;
    bytes32 hash;
}

interface ITambolaTambola {
    event GameCreated(uint256 indexed gameId, address indexed host, uint64 startTime, uint256 ticketPrice);
    event GameEndedNoWinner(uint256 indexed gameId);
    event GameWon(uint256 indexed gameId, address indexed winner, uint256 payout, address host, uint256 hostFee);
    event LineWon(uint256 indexed gameId, uint8 line, address indexed winner, uint256 payout);
    event NumberDrawn(uint256 indexed gameId, uint8 number, uint64 drawnAt);
    event RefundClaimed(uint256 indexed gameId, address indexed player, uint256 amount);
    event TicketBought(uint256 indexed gameId, address indexed player, uint256 ticketId, bytes32 hash);
    event Withdrawn(address indexed to, uint256 amount);
    function DRAW_INTERVAL_SECONDS() external view returns (uint16);
    function FULLHOUSE_BPS() external view returns (uint16);
    function HOST_BPS() external view returns (uint16);
    function LINE_BPS() external view returns (uint16);
    function MAX_NUMBER() external view returns (uint8);
    function MAX_TICKETS() external view returns (uint8);
    function buyTicket(uint256 gameId, uint8[27] calldata layout) external payable;
    function claimRefund(uint256 gameId) external;
    function createGame(uint256 startTimestamp, uint256 ticketPrice) external returns (uint256);
    function drawNumber(uint256 gameId) external;
    function getDrawnNumbers(uint256 gameId) external view returns (uint8[] memory);
    function getGame(uint256 gameId) external view returns (ITambolaGameView memory);
    function getTickets(uint256 gameId) external view returns (ITambolaTicket[] memory);
    function getTicketsByOwner(uint256 gameId, address player) external view returns (uint256[] memory, ITambolaTicket[] memory);
    function isRefundClaimed(uint256 gameId, address player) external view returns (bool);
    function isTicketHashUsed(uint256 gameId, bytes32 hashValue) external view returns (bool);
    function nextGameId() external view returns (uint256);
    function withdraw() external;
    function withdrawable(address arg0) external view returns (uint256);
}

library TambolaTambola {
    address internal constant ADDRESS = 0x6b383C507a7cde394279EC598038bDF9AD0681e7;

    function ref() internal pure returns (ITambolaTambola) {
        return ITambolaTambola(ADDRESS);
    }

    function cdm() internal pure returns (ITambolaTambola) {
        return ref();
    }
}
